### ISSUE TITLE
[Enhancement] Sending a PnP Command needs to be blocked properly if validation fails

### ISSUE THREAD

**Issue by jspaith** [Azure/azure-iot-explorer#440] opened 2021-05-05 17:19 UTC
On IoT Explorer 0.14.3.0, Windows 10.

**To Reproduce**
1) Connect a device with the PnP sample for temperature controller.  Though in practice anything with a DTDLv2 with a date/time I think should repo.  Note I'm using embedded C SDK but I don't think that's issue.
2) Navigate to the device=>IoT Plug and Play Components=>thermostat1=>Commands.
3) Enter in the date, but only enter the month/day/year.  Leave the hour/minute/second stuff blank.
4) Click send-command.  On the device, an empty JSON document will be received which isn't legal for DTDLv2 model.  
Note that if you fill out the hh/mm/ss stuff then non-empty JSON is happily sent.

**Expected behavior**
Either IoT Explorer should complain if it expects the hh/mm/ss, or it should have some default so that valid JSON is always sent.

See below for screenshot shows my repro right before I submit.

![repo-screen](https://user-images.githubusercontent.com/27444433/117182382-82220f00-ad93-11eb-8b61-55de97909f3a.PNG)

**Comment by rido-min** [comment] 2021-05-05 17:45
Thanks John.

Yes, IoT Explorer should not try to invoke any command or property if the input parameters are not validated.

However I see a different behavior, when I dont set the time, I got a timeout and no bytes are received on the device.

![image](https://user-images.githubusercontent.com/14916339/117185683-f312f800-ad8e-11eb-9028-f4b4bade527f.png)

**Comment by jspaith** [comment] 2021-05-06 18:29
@rido-min - which device SDK are you using?  I know that some of them don't play well when a 0 length body JSON is sent to it.

@digimaun did a lot of investigation around this - for instance [this](https://github.com/Azure/azure-iot-sdk-c/issues/1924) on C side.

**Comment by rido-min** [comment] 2021-05-06 18:40
I'm using https://mqtt.rido.dev :) this is not processing the method payload [code](https://github.com/ridomin/iothub-webclient/blob/master/AzIoTHubClient.js#L119)

**Comment by YingXue** [comment] 2022-07-26 17:21
Is it a SDK specific issue? I looks like Explorer is not sending any data if time is not set from Rido's comments above and this is the expected behavior to me. Please feel free to reopen if I misunderstood.

**Comment by rido-min** [comment] 2022-07-26 19:45
I cannot repro, seems the dateTime picker does not allow to select without time.

**Comment by jspaith** [comment] 2022-07-26 20:17
@rido-min / @YingXue - I just installed the latest IoT Explorer (0.14.10.0) and the issue still persists.

To be clear, the issue is that if in IoT Explorer with the dateTime picker I *only* select the date but NOT the time, then IoT Explorer will end up sending empty JSON to the device.  There's no date even sent here, never mind time.

Looking at what the C SDK shows (though this shouldn't be SDK specific) on the callback.  See the `payloadLength` below.

```
0:000> kc
 # Call Site
00 pnp_temperature_controller!PnP_TempControlComponent_CommandCallback
01 pnp_temperature_controller!invoke_command_callback
02 pnp_temperature_controller!IoTHubClientCore_LL_DeviceMethodComplete
03 pnp_temperature_controller!processDeviceMethodNotification
04 pnp_temperature_controller!mqttNotificationCallback
05 pnp_temperature_controller!ProcessPublishMessage
06 pnp_temperature_controller!recvCompleteCallback

0:000> ?? commandRequest
struct IOTHUB_CLIENT_COMMAND_REQUEST_TAG * 0x000000ba`624feea8
   +0x000 structVersion    : 0n1
   +0x008 componentName    : 0x0000029f`ac230130  "thermostat1"
   +0x010 commandName      : 0x0000029f`ac218edc  "getMaxMinReport"
   +0x018 payload          : (null) 
   +0x020 payloadLength    : 0

```

**Comment by jspaith** [comment] 2022-07-26 20:18
If you can repro along steps provided, could you please re-activate?  Thanks

**Comment by YingXue** [comment] 2022-07-26 20:26
I see what you mean now. Since dtdl is saying it's a datetime, we do need users to enter both date and the time so the validation would pass and send the json body. 
There is slient validation in place, and sending empty body if validation fails is expected. We didn't implement blocking logic in this case.

**Comment by YingXue** [comment] 2022-09-06 21:08
Fix rolled out: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.14.14
Closing

**Closed by YingXue** 2022-09-06 21:08 UTC
Labels: enhancement, backlog, Plug and Play, In progress

**Comment by jspaith** [comment] 2022-09-06 21:31
Just verified that the fix works as promised.  Thanks @YingXue !
