### ISSUE TITLE
[BUG] UI hangs when subscribing to telemetry for an interface when multiple telemetries are sent in same message

### ISSUE THREAD

**Issue by kartben** [Azure/azure-iot-explorer#176] opened 2019-12-20 19:54 UTC
```
{
  "body": {
    "humidity": 60,
    "objectTemp": 21
  },
  "enqueuedTime": "2019-12-20T19:52:57.206Z",
  "systemProperties": {
    "iothub-connection-device-id": "00:12:4B:00:1C:AB:50:97",
    "iothub-connection-auth-method": "{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}",
    "iothub-connection-auth-generation-id": "637124555173258296",
    "iothub-enqueuedtime": 1576871576987,
    "iothub-message-source": "Telemetry",
    "iothub-interface-name": "lpstkSensors",
    "x-opt-sequence-number": 6131,
    "x-opt-offset": "3050064",
    "x-opt-enqueued-time": 1576871577206
  }
}
```

This will crash the Telemetry UI for this interface whereas if I only send humidity or objectTemp, this works as expected.

**Comment by YingXue** [comment] 2019-12-26 19:41
Hi @kartben 
Can you help provide the interface definition for telemetry?
If the "@type": "Telemetry" in your interface only defined 'objectTemp', then 'humidity' is not expected to be sent as the body.
But anyways the UI should not crash, which is an valid bug.
If you can help provide the interface definition, it can help us repro the bug.

**Comment by YingXue** [comment] 2019-12-26 19:41
> Hi @kartben
> Can you help provide the interface definition for telemetry?
> If the "@type": "Telemetry" in your interface only defined 'objectTemp', then 'humidity' is not expected to be sent as the body.
> But anyways the UI should not crash, which is an valid bug.
> If you can help provide the interface definition, it can help us repro the issue and get it property fixed.

**Comment by kartben** [comment] 2020-01-06 15:34
Hi @YingXue 
Repro is pretty straightforward with any SDK that has support for "imploded" telemetry, for example: https://github.com/Azure/azure-iot-sdk-node/blob/digitaltwins-preview/digitaltwins/samples/device/javascript/sample_device.js

Regarding your question, my interface lpstkSensors does have the various telemetries described in it (see model here: https://github.com/kartben/lpstk_azureiot_bridge/blob/master/lpstksensors.js

Thanks!

**Comment by YingXue** [comment] 2020-01-07 20:55
@kartben 
I've spotted the issue with the new node SDK you've provided above.
Azure iot explorer tool has a validation, which would only render the telemetry body when the key matches. Let me give you an working example:
`{
  "body": {
    "humid": 0
  },
  "enqueuedTime": "2020-01-07T20:52:29.175Z",
  "properties": {
    "iothub-message-schema": "humid"
  }
}`
'humid' is specifed as an 'iothub-message-schema', so it will show property in the temeletry table:
![image](https://user-images.githubusercontent.com/5489222/71928630-c2945d00-314c-11ea-8cc1-c01c11fdb57a.png)

However, running the sample sdk, the raw telemetry without the property set
`{
  "body": {
    "temp": 36.373756160704986,
    "humid": 70.37907786824884
  },
  "enqueuedTime": "2020-01-07T20:50:48.723Z",
  "properties": {}
}`
Thus it won't be able to mapped properly.
Please let me know if it helps. Meanwhile, let me confirm with the SDK team of this behavior.

**Comment by kartben** [comment] 2020-01-07 21:02
@YingXue since the message has the iothub-interface-name system property set hopefully the tool has all it needs to display all the properties for which the key is also found in the associated interface schema, and silently filter/ignore all the properties? But you are right that it's worth checking with SDK team that the format for how 'imploded' messages should look like is now final.
FWIW I would provide a patch but I'm not familiar enough with React to be sure I would be following best practices :)

**Comment by YingXue** [comment] 2020-01-07 21:10
@kartben 
A very good point, I will update the UI to render error message in this case after confirming with the SDK team.
If you would like to take a look at the code, this is where the check is [https://github.com/Azure/azure-iot-explorer/blob/e6ba1633134d324a177921de8a6d19f69c6c5e43/src/app/devices/deviceContent/components/deviceEvents/deviceEventsPerInterface.tsx#L364](url)
I've commented out the check, which you can also do to get yourself unblocked, but you'll see the following error in the table:
![image](https://user-images.githubusercontent.com/5489222/71929646-f2446480-314e-11ea-81e5-2bcbff4e6b3d.png)
As the key was not populated, the error message is not a complete sentence :)

**Comment by YingXue** [comment] 2020-01-08 20:54
Hi @kartben 
The fix has now been release if you'd like to check it out [https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.11](url).
Thank you for opening this issue. I will now close it.

**Comment by kartben** [comment] 2020-01-09 09:04
Hi @YingXue 

I don't think this fixes the issue I originally reported. Did you try with the NodeJS sample I mentioned earlier? If you subscribe to the telemetry for the `urn:contoso:com:EnvironmentalSensor:1` interface it still crashes.

Also, I think I need to clarify the behavior I'd be expecting for messages that contain multiple telemetries. I will be using the same [sample_device.js](https://github.com/Azure/azure-iot-sdk-node/blob/digitaltwins-preview/digitaltwins/samples/device/javascript/sample_device.js) example previously mentioned in the thread.
When multiple telemetry is sent by the SDK (`environmentalSensor.sendTelemetry( { temp: 10 + (Math.random() * 90), humid: 1 + (Math.random() * 99) } );`), the following message is sent under the hood:

```json
{
  "body": {
    "temp": 25.83140795255571,
    "humid": 29.572878173901277
  },
  "enqueuedTime": "2020-01-09T08:53:28.306Z",
  "systemProperties": {
    "iothub-connection-device-id": "pnpbootcamp",
    "iothub-connection-auth-method": "{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}",
    "iothub-connection-auth-generation-id": "637140753051540227",
    "iothub-enqueuedtime": 1578560008228,
    "iothub-message-source": "Telemetry",
    "iothub-interface-name": "environmentalSensor",
    "x-opt-sequence-number": 11880,
    "x-opt-offset": "7148344",
    "x-opt-enqueued-time": 1578560008306
  }
}
```

IoT Hub Explorer should look at iothub-interface-name system property, realize it knows the schema for `environmentalSensor`, and use it to create one row per actual telemetry item, e.g.:

![image](https://user-images.githubusercontent.com/128251/72053477-699d0400-32c7-11ea-829f-5689735b46fd.png)
 

Can you please re-open the issue?

**Comment by YingXue** [comment] 2020-01-09 18:53
Hi @kartben 
Feel free to reopene the issue anytime if your issue is not addressed.
I've ran this sample that you've provided: https://github.com/Azure/azure-iot-sdk-node/blob/digitaltwins-preview/digitaltwins/samples/device/javascript/sample_device.js
This is the raw telemetry data that I am seeing 
![image](https://user-images.githubusercontent.com/5489222/72095395-3e1d1800-32cd-11ea-8061-a8ba736c172e.png)

As I mentioned earlier, explorer look for **iothub-message-schema** in **properties**, **not iothub-interface-name** in **system properties**.
I've talked to the SDK team yesterday, and verified that containing multiple telemetry entries in one body is newly added to accomendate so-called 'message explosion'.
However this tool is not designed to be able to handle this yet. As we look for  **iothub-message-schema in properties**, the tool as it's currently, is verifying if the key is the same as specified in **iothub-message-schema,** and verify if the data type is correct not, it is not able to handle multiple entries at this point.
This is a bigger design issue I need to talk to more people before we can provide an update.
However, I am concerned about the crashing issue more. Unfortunately, I am not able to repro the crashing issue, The following is what I am seeing while running the sample from the link above
![image](https://user-images.githubusercontent.com/5489222/72095651-c13e6e00-32cd-11ea-8f25-2b4aed585127.png)

**Comment by digimaun** [comment] 2020-01-09 19:24
@kartben , until the issue is resolved here...as a workaround, maybe monitoring messages via Azure CLI + IoT extension will suffice? `az iot hub monitor-events`

**Comment by YingXue** [comment] 2020-01-09 22:00
@kartben 
I think I may know what's happening here. The difference between your data and mine is yours doesn't have 'properties' at all, not to mention any key in it. 
I can provide a fix rather soon to fix the crashing issue. But a proper validation would have to wait. Please let me know if you'd like a hot fix, or don't mind a later one til we fix with updated validation.

Meanwhile, if you'd like to use it locally or build a package for yourself, you can change the following line in this file: [https://github.com/Azure/azure-iot-explorer/blob/49f6ad181f44dc61a47af30c19e1f8b0978233eb/src/app/devices/deviceContent/components/deviceEvents/deviceEventsPerInterface.tsx#L302](url)
from
`{this.renderMessageBody(event, context, event.properties[TELEMETRY_SCHEMA_PROP], parsedSchema)}`
to 
`{this.renderMessageBody(event, context, event.properties && event.properties[TELEMETRY_SCHEMA_PROP] || null, parsedSchema)}`

**Comment by kartben** [comment] 2020-01-10 08:56
> @kartben , until the issue is resolved here...as a workaround, maybe monitoring messages via Azure CLI + IoT extension will suffice? `az iot hub monitor-events`
> 
> Edit:
> Example to show all message annotations + properties
> 
> `az iot hub monitor-events -n YourHubName --props all`

Thanks for the suggestion. Actually there is already an "easy" similar workaround while staying in IoT Explorer -- one can easily subscribe to all "Telemetry" instead of the telemetry section of each interface, this way raw messages can easily be monitored and there is obviously no issue as there's no PnP at play there.

**Comment by YingXue** [comment] 2020-01-10 21:33
Hi @kartben 
The crashing fix has been checked into master. I will make a release early next week and let you know. And meanwhile please feel free to use the master branch if you'd like.
However the validation and message enrichment (populating columns) would have to wait bit longer. Internally, the feature is still being designed and implemented, and the device simulator has not yet incorporated the change, thus us downstream is not yet able to parse and enrich the new type of telemetry body properly.

**Comment by YingXue** [comment] 2020-01-23 23:12
Release [https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.12](https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.12) has the update out. Please check it out. Closing the issue here.
As mentioned earlier, the fix is only to address the crashing issue. The enrichment of events would come after.

**Closed by YingXue** 2020-01-23 23:12 UTC
Labels: enhancement

**Comment by YingXue** [comment] 2020-02-25 23:07
Hi @kartben 
#223 has addressed the enriching exploded pnp message. The screenshot in the link illustrated the idea.

The latest bits has been release: https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.15
