### ISSUE TITLE
[BUG] Default timeout values for direct method invocation shouldn't be 0 second.

### ISSUE THREAD

**Issue by kartben** [Azure/azure-iot-explorer#205] opened 2020-01-23 15:09 UTC
Right now "Connection timeout in seconds" and "Response timeout in seconds" are both zero by default. This causes issues as command are not even sent to the device and service immediately answers with an error "responseTimeoutInSeconds must be within [5; 300].".

I suggest to have both default values set to 10 seconds, like it is in the portal UI.

**Comment by YingXue** [comment] 2020-01-23 21:55
Hi @kartben 
We will look into change the default to a different value. Though i do want to point out that this is not a bug as user have the flexibility to change the value by using the slides.

**Comment by YingXue** [comment] 2020-01-23 23:11
Release [https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.12](https://github.com/Azure/azure-iot-explorer/releases/tag/v0.10.12) has the update out. Please check it out. Closing the issue here.

**Closed by YingXue** 2020-01-23 23:11 UTC
Labels: by design, enhancement
