### ISSUE TITLE
[Bug] Azure IoT Explorer Preview 0.14.2

### ISSUE THREAD

**Issue by Zherokt** [Azure/azure-iot-explorer#437] opened 2021-04-23 08:24 UTC
I just updated from 0.14.1 to 0.14.2 using the released dmg file in my MacBook Pro running Catalina 10.15.7

While the .1 version was running fine, .2 can not retrieve any of my IoTHubs device list, even if I create a new IoTHub or a new connection to an existing one within the Explorer app. That would be okay if it wasn't because when rolling back to .1 i have the exact same problem from now.

When I click on any of my IoTHubs to see my devices I get the following notification:

<img width="263" alt="Captura de pantalla 2021-04-23 a las 5 20 46 p  m" src="https://user-images.githubusercontent.com/26620935/115842026-609e5a80-a458-11eb-90fc-2dcbafa5127a.png">

I have also tried closing the app, killing the process that runs in port 8081 and re open.

Do you have any suggestions? Thank you guys!

**Comment by montgomp** [comment] 2021-04-23 15:45
Thanks for reporting this regression. I've marked 0.14.2 as a pre-release and I'm working to find the cause and fix ASAP.

**Comment by montgomp** [comment] 2021-04-23 16:14
This regression occurs when the environment variable "AZURE_IOT_EXPLORER_PORT" is not set. Short-term fix is to add the environment variable or to revert to 0.14.1 and follow the instructions below to set the port in local storage.

1. Open IoT Explorer 0.14.1 (or earlier)
2. Open Developer Tools from the Help menu.
3. Navigate to the Application tab.
4. In the left navigation, expand Local Storage and click on "file://"
5. Set CUSTOM_CONTROLLER_PORT to 8081.
6. Restart IoT Explorer 0.14.1 (or earlier).

I'll issue a new release once I run through some more testing.

**Comment by montgomp** [comment] 2021-04-24 00:01
This should be resolved in v0.14.3.  https://github.com/Azure/azure-iot-explorer/releases/tag/v0.14.3

**Closed by montgomp** 2021-04-24 00:01 UTC
Labels: bug
